import type { User } from '../types';

export const mockEmployees: User[] = [
  {
    id: 'emp-1',
    name: 'Алексей Морозов',
    role: 'owner',
    email: 'alexey@cafeflow.demo',
    phone: '+7 (916) 234-56-78',
    hourlyRate: 0,
    status: 'active',
    hireDate: '2020-03-15',
    permissions: ['all'],
  },
  {
    id: 'emp-2',
    name: 'Марина Козлова',
    role: 'manager',
    email: 'marina@cafeflow.demo',
    phone: '+7 (903) 456-78-90',
    hourlyRate: 350,
    status: 'active',
    hireDate: '2021-06-01',
    permissions: ['manage_shifts', 'manage_menu', 'view_reports', 'manage_tables'],
  },
  {
    id: 'emp-3',
    name: 'Дмитрий Волков',
    role: 'waiter',
    email: 'dmitry@cafeflow.demo',
    phone: '+7 (925) 789-01-23',
    hourlyRate: 200,
    status: 'active',
    hireDate: '2022-04-10',
    permissions: ['manage_tables', 'create_orders'],
  },
  {
    id: 'emp-4',
    name: 'Екатерина Смирнова',
    role: 'waiter',
    email: 'kate@cafeflow.demo',
    phone: '+7 (916) 321-54-76',
    hourlyRate: 200,
    status: 'active',
    hireDate: '2022-09-20',
    permissions: ['manage_tables', 'create_orders'],
  },
  {
    id: 'emp-5',
    name: 'Иван Петров',
    role: 'cashier',
    email: 'ivan@cafeflow.demo',
    phone: '+7 (903) 654-32-10',
    hourlyRate: 250,
    status: 'active',
    hireDate: '2023-01-15',
    permissions: ['manage_payments', 'view_orders'],
  },
  {
    id: 'emp-6',
    name: 'Ольга Нечаева',
    role: 'waiter',
    email: 'olga@cafeflow.demo',
    phone: '+7 (925) 111-22-33',
    hourlyRate: 200,
    status: 'on_break',
    hireDate: '2023-05-01',
    permissions: ['manage_tables', 'create_orders'],
  },
  {
    id: 'emp-7',
    name: 'Сергей Тихонов',
    role: 'waiter',
    email: 'sergey@cafeflow.demo',
    phone: '+7 (916) 999-88-77',
    hourlyRate: 200,
    status: 'inactive',
    hireDate: '2023-07-12',
    permissions: ['manage_tables', 'create_orders'],
  },
];

export const demoRoles = [
  { role: 'owner' as const, label: 'Владелец', description: 'Полный доступ к системе', employee: mockEmployees[0] },
  { role: 'manager' as const, label: 'Менеджер', description: 'Управление сменами и командой', employee: mockEmployees[1] },
  { role: 'cashier' as const, label: 'Кассир', description: 'Оплаты и кассовые операции', employee: mockEmployees[4] },
  { role: 'waiter' as const, label: 'Официант', description: 'Столы и заказы', employee: mockEmployees[2] },
];
